import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
	BRAND_COLORS,
	ICON_VIEWBOX,
	iconInner,
	iconSvg,
	sshConfigEntry,
	sshSetupPrompt,
	theme
} from "../index.ts";
import { formatContent } from "../../../scripts/write-formatted.mjs";

// `--check` verifies committed text assets and unavoidable literal copies still
// match theme.json through the generated theme export.
// guard, wired into `pnpm check`) instead of writing. Every output of this script
// is deterministic from index.ts, so the check covers all of them; the font- and
// sharp-derived assets (logo.mjs, icons.mjs) stay outside this script.
function cssVariableName(key) {
	return key
		.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
		.replace(/([a-z])([0-9])/g, "$1-$2");
}

function cssThemeBlock(selector, values) {
	const lines = Object.entries(values).map(
		([key, value]) => `\t--${cssVariableName(key)}: ${value};`
	);
	return `${selector} {\n${lines.join("\n")}\n}`;
}

function webThemeCss() {
	return `/* AUTO-GENERATED by packages/shared/scripts/sync.mjs - do not edit by hand.
   Source: packages/shared/theme.json. */
${cssThemeBlock(":root", theme.light)}

${cssThemeBlock(".dark", theme.dark)}
`;
}

// Per-scheme variables for the auth/error pages.
function idePageSchemeVars(c) {
	return {
		"--vscode-button-background": c.button,
		"--vscode-button-foreground": c.buttonForeground,
		"--vscode-button-hoverBackground": c.buttonHover,
		"--vscode-focusBorder": c.ring,
		"--vscode-editor-background": c.background,
		"--vscode-editorHoverWidget-background": c.popover,
		"--vscode-editorHoverWidget-border": c.border,
		"--vscode-editorHoverWidget-foreground": c.popoverForeground,
		"--vscode-errorForeground": c.destructive,
		"--vscode-descriptionForeground": c.mutedForeground,
		"--auth-success": c.success,
		"--auth-warning": c.warning,
		"--auth-input-focus": c.ring,
		"--vscode-foreground": c.foreground,
		"--vscode-input-background": c.field,
		"--vscode-input-border": c.fieldBorder,
		"--vscode-input-foreground": c.fieldForeground,
		"--vscode-toolbar-activeBackground": `${c.mutedForeground}50`,
		"--vscode-toolbar-hoverBackground": c.hover,
		"--vscode-shadow-hover": `0 2px 8px ${c.shadow}`,
		"--composery-selection": c.selection,
		"--composery-scrollbar-track": c.scrollbarTrack,
		"--composery-scrollbar": c.scrollbar,
		"--composery-scrollbar-hover": c.scrollbarHover,
		"--composery-scrollbar-active": c.scrollbarActive
	};
}

function idePageThemeCss() {
	const cssVars = (vars, indent) =>
		Object.entries(vars)
			.map(([k, v]) => `${indent}${k}: ${v};`)
			.join("\n");
	const lightVars = idePageSchemeVars(theme.light);
	const darkVars = idePageSchemeVars(theme.dark);
	// Stryker disable next-line StringLiteral: formatContent applies the committed CSS indentation after this template is assembled.
	const indent = "\t";
	// Stryker disable next-line StringLiteral: formatContent applies the committed CSS indentation after this template is assembled.
	const nestedIndent = "\t\t";

	return `/* AUTO-GENERATED by packages/shared/scripts/sync.mjs - do not edit by hand.
   Source: packages/shared/theme.json. */
:root {
	color-scheme: light dark;
${cssVars(lightVars, indent)}
	--vscode-cornerRadius-medium: 6px;
	--vscode-toolbar-hoverOutline: transparent;
}

@media (prefers-color-scheme: dark) {
	:root {
${cssVars(darkVars, nestedIndent)}
	}
}

`;
}

// Browser favicon that follows the colour scheme (like github.com and
// polar.sh): a dark mark on a light UI, a light mark on a dark UI. It takes two
// kinds of file, because neither can do both jobs.
//
// The adaptive one carries its own prefers-color-scheme rule, so it is right on
// first paint and with JS off; this is the file pages declare. The scheme-pinned
// pair is one fixed colour each: Chromium rasterizes a favicon once per URL and
// never re-runs the embedded media query, so the adaptive file alone only ever
// changes across a reload. The favicon scripts point the link at a pinned file
// instead, and a new URL is something every browser does re-render.
//
// Pages must declare the .ico fallback FIRST with an explicit sizes attribute
// and the adaptive SVG LAST with sizes="any" - Chromium picks an unsized (or
// later-listed) ICO over the SVG and the tab icon stops following the colour
// scheme.
const adaptiveFavicon = ({ width = 256, height = 256 } = {}) =>
	`<svg width="${width}" height="${height}" viewBox="${ICON_VIEWBOX}" fill="none" xmlns="http://www.w3.org/2000/svg"><style>svg{color:${BRAND_COLORS.icon.light}}@media (prefers-color-scheme:dark){svg{color:${BRAND_COLORS.icon.dark}}}</style>${iconInner()}</svg>`;

const pinnedFavicon = ({ scheme, width = 256, height = 256 }) =>
	iconSvg({ color: BRAND_COLORS.icon[scheme], height, width });

// The SSH setup prompt, as a module a builtin extension can require.
//
// The extension is plain JavaScript running in the extension host; the prompt is
// TypeScript in `shared` because the website renders the same text and a second
// copy would drift silently - each surface would go on producing a prompt that
// worked. Emitting it keeps one source.
//
// `Function.prototype.toString()` is what makes that cheap. Node runs these
// modules by erasing types to whitespace rather than removing them, so a
// function's own source is already valid JavaScript; there is no transpiler here
// and nothing to keep in step with one.
function sshPromptModule() {
	return `// AUTO-GENERATED by packages/shared/scripts/sync.mjs - do not edit by hand.
// Source: packages/shared/ssh.ts.
${sshConfigEntry.toString()}

${sshSetupPrompt.toString()}

module.exports = { sshConfigEntry, sshSetupPrompt };
`;
}

export async function syncAssets({
	// Stryker disable next-line StringLiteral: this default is CLI argument wiring; behavior tests pass the check decision explicitly.
	check = process.argv.includes("--check"),
	root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..")
} = {}) {
	const webApp = join(root, "packages", "web", "app");
	const webPublic = join(root, "packages", "web", "public");
	const ideBrowser = join(root, "packages", "ide", "overlay", "src", "browser");
	const ideMedia = join(ideBrowser, "media");
	const stale = [];

	async function emit(path, content) {
		const formatted = await formatContent(path, content);
		if (!check) {
			await writeFile(path, formatted);
			return;
		}
		// Stryker disable next-line ArrowFunction: null and undefined both differ from every formatted string and therefore both mark a missing output stale.
		const current = await readFile(path, "utf8").catch(() => null);
		if (current !== formatted) stale.push(relative(root, path));
	}

	await emit(join(webApp, "brand.css"), webThemeCss());

	await emit(
		join(
			root,
			"packages",
			"ide",
			"overlay",
			"lib",
			"vscode",
			"extensions",
			"composery-ssh",
			"prompt.js"
		),
		sshPromptModule()
	);

	for (const name of ["auth.html", "error.html"]) {
		const path = join(ideBrowser, "pages", name);
		let page = await readFile(path, "utf8");
		for (const [scheme, color] of [
			["light", theme.light.background],
			["dark", theme.dark.background]
		]) {
			const pattern = new RegExp(
				`(name="theme-color"\\s+content=")#[0-9a-f]{6}("\\s+media="\\(prefers-color-scheme: ${scheme}\\)")`,
				"i"
			);
			const matches = page.match(new RegExp(pattern.source, "gi")) ?? [];
			if (matches.length !== 1)
				throw new Error(
					`${name} ${scheme} theme-color: expected one palette literal, found ${matches.length}`
				);
			page = page.replace(pattern, `$1${color}$2`);
		}
		await emit(path, page);
	}

	await emit(join(ideBrowser, "pages", "brand.css"), idePageThemeCss());

	function replaceOne(source, pattern, replacement, name) {
		const matches = source.match(new RegExp(pattern.source, "g")) ?? [];
		if (matches.length !== 1)
			throw new Error(
				`${name}: expected one palette literal, found ${matches.length}`
			);
		return source.replace(pattern, replacement);
	}

	const readinessPath = join(
		root,
		"packages",
		"ide",
		"overlay",
		"src",
		"node",
		"persistence",
		"readiness.ts"
	);
	let readiness = await readFile(readinessPath, "utf8");
	for (const [name, pattern, replacement] of [
		[
			"startup light",
			/(body\{margin:0;background:)#[0-9a-f]{6}(;color:)#[0-9a-f]{6}/i,
			`$1${theme.light.background}$2${theme.light.foreground}`
		],
		[
			"startup dark",
			/(@media \(prefers-color-scheme:dark\)\{body\{background:)#[0-9a-f]{6}(;color:)#[0-9a-f]{6}/i,
			`$1${theme.dark.background}$2${theme.dark.foreground}`
		]
	])
		readiness = replaceOne(readiness, pattern, replacement, name);
	await emit(readinessPath, readiness);

	await emit(join(webApp, "icon.svg"), `${adaptiveFavicon()}\n`);
	await emit(join(webPublic, "icon-light.svg"), `${pinnedFavicon({})}\n`);
	await emit(
		join(webPublic, "icon-dark.svg"),
		`${pinnedFavicon({ scheme: "dark" })}\n`
	);

	// The editor's favicons size themselves off the <link>, not a fixed box.
	const ideFaviconBox = { width: "100%", height: "100%" };
	await emit(
		join(ideMedia, "favicon.svg"),
		`${adaptiveFavicon(ideFaviconBox)}\n`
	);
	await emit(
		join(ideMedia, "favicon-light.svg"),
		`${pinnedFavicon({ ...ideFaviconBox })}\n`
	);
	await emit(
		join(ideMedia, "favicon-dark.svg"),
		`${pinnedFavicon({ scheme: "dark", ...ideFaviconBox })}\n`
	);

	if (check) {
		if (stale.length) {
			console.error(
				`Brand assets are stale - run \`pnpm fix:assets\`:\n${stale
					.map((path) => `  ${path}`)
					.join("\n")}`
			);
			process.exit(1);
		}
		console.log("Brand assets are up to date.");
	} else {
		console.log("Synced generated brand CSS and SVGs.");
	}
}

// Stryker disable next-line all: package scripts exercise this CLI dispatch; behavior tests call the generator directly so they can assert write and check modes separately.
if (resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url))
	await syncAssets();
